In [1]:
import numpy as np

In [2]:
import random as rnd
data_list = [rnd.randint(1, 100) for _ in range(25)]

## 1. Create a Numpy array from a list of integers

In [3]:
np_array = np.array(data_list)
print(np_array)

[78 58 19 81 48 79 57 37 27 65 70 31 23 21 90 64 30 54 22 78 32 10 28 35
  5]


## 2. Difference between arange(), linspace(), and logspace()

In [4]:
# np.arange(start, stop, step) creates an array with envenly spaced values within a range (excluding stop)
# use arange() when you need fixed step size

arr = np.arange(1, 10, 2)
print(arr)

[1 3 5 7 9]


In [5]:
# np.linspace(start, stop, num, endpoint) creates an array with nu, evenly spaces values between start and stop
# use linspace() when you need a specific number of values

arr = np.linspace(1, 10, 5, endpoint=True)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [6]:
# np.logspcae(start, stop, num, base)
# use logspace() when you need logarithmic scaling

arr = np.logspace(1, 3, 4) # 10^1 to 10^3 with 4 values
print(arr)

[  10.           46.41588834  215.443469   1000.        ]


## 3. Reshape a 1D array into a 2D matrix

In [7]:
arr = np.array(data_list)
matrix = arr.reshape(5, 5)
print(matrix)

[[78 58 19 81 48]
 [79 57 37 27 65]
 [70 31 23 21 90]
 [64 30 54 22 78]
 [32 10 28 35  5]]


## 4. Find Mean, Median and Standard deviation of a NumPy array

In [8]:
arr = np.arange(1, 20, 2)

mean_val = np.mean(arr)
median_val = np.median(arr)
std_val = np.std(arr)

print(f'Mean : {mean_val}\nMedian : {median_val}\nStandard Deviation : {std_val}\n')

Mean : 10.0
Median : 10.0
Standard Deviation : 5.744562646538029



## 5. Perform element-wise addition and multiplication of two arrays  

In [9]:
arr1 = np.arange(1, 10, 2)
arr2 = np.arange(2, 11, 2)

In [10]:
add = arr1 + arr2 # or, np.add(arr1, arr2)
mul = arr1 * arr2 # or, np.multiply(arr1, arr2)

print('Arr1 : ', arr1)
print('Arr2 : ', arr2)
print("Addition : ", add)
print("Multiplication : ", mul)

Arr1 :  [1 3 5 7 9]
Arr2 :  [ 2  4  6  8 10]
Addition :  [ 3  7 11 15 19]
Multiplication :  [ 2 12 30 56 90]


## 6. Linear Algebra

In [13]:
dot_prod = np.dot(arr1, arr2)
inv_matrix = np.linalg.inv(matrix)
dig_matrix = np.diag([1, 2, 3])
eigen_values, eigen_vectors = np.linalg.eig(matrix)

print('Dot product : ', dot_prod)
print('\nInverse :\n', inv_matrix)
print("\nDiagonal matrix :\n", dig_matrix)
print('\nEigen values : ', eigen_values)
print('\nEigen vectors :\n', eigen_vectors)

Dot product :  190

Inverse :
 [[-0.02963979  0.0266593   0.04155903 -0.05565169  0.05807483]
 [ 0.01777461  0.01634108 -0.0377548   0.02188199 -0.04484303]
 [-0.00109289 -0.00131021 -0.02525468  0.03095335 -0.00076359]
 [ 0.02114121 -0.02511365 -0.00698835  0.01643806 -0.00712145]
 [ 0.01227715 -0.02016892 -0.00012356  0.02400167 -0.02786657]]

Diagonal matrix :
 [[1 0 0]
 [0 2 0]
 [0 0 3]]

Eigen values :  [227.45462394 +0.j          24.95493575 +0.j
 -16.5542565 +15.26439301j -16.5542565 -15.26439301j
 -34.30104667 +0.j        ]

Eigen vectors :
 [[ 0.56442906+0.j         -0.22670757+0.j          0.66472972+0.j
   0.66472972-0.j         -0.22604065+0.j        ]
 [ 0.50876903+0.j         -0.76576315+0.j         -0.34167605-0.05615414j
  -0.34167605+0.05615414j  0.02824795+0.j        ]
 [ 0.41582824+0.j          0.22436114+0.j         -0.07297408-0.42710246j
  -0.07297408+0.42710246j -0.74610351+0.j        ]
 [ 0.4453857 +0.j          0.44153045+0.j         -0.39395775+0.17441642j
  -